sudo: required

os:
  - linux

dist: trusty

services:
  - docker

language: cpp

compiler:
  - gcc

before_install:
  - docker pull ubuntu

before_script:
- if [ $TRAVIS_OS_NAME == linux ]; then travis_retry make test; fi

script: 
  - docker version
  - docker ps -a
  - docker exec make test
  - docker exec ./oTravis
  - docker exec ls -l
  - docker stop ubuntu
  - docker ps -a

notifications:
  email: false
