sudo: required

os: linux

dist: trusty

services: docker

language: cpp

compiler: gcc

before_install:
  - docker pull ubuntu:latest
  # C++14
  # - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  # - sudo apt-get update -qq

install:
  # C++14
  # - sudo apt-get install -y build-essential
  # - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

before_script:
#  - make test
#  - ./oTravis
  - pwd
  - ls -l
#  - uname -a
  - cat Makefile

script: 
#  - docker version
  - docker images
#  - docker run -e JAVA_OPTS='-Duser.timezone=America/Vancouver' -d -t --name=ub1604 ubuntu
#  - docker run ubuntu
  - docker ps -a
#  - docker exec ub1604 apt-get install -y g++
  - docker exec ub1604 date
  - docker exec ub1604 pwd
#  - docker exec ub1604 ls -l /usr/bin | grep g++
#  - docker exec ub1604 make test
#  - docker exec ub1604 ./oTravis
  - docker exec ub1604 ls -l
#  - docker exec ub1604 cd /home
  - docker exec ub1604 ls -l
#  - docker exec ub1604 gcc --version
#  - docker exec ububtu ./oTravis
  - docker stop ub1604
  - docker ps -a
#  - docker run -it ubuntu
#  - apt-get update
#  - uname -a
#  - make test
  

notifications:
  email: false
