language: cpp

sudo: required

dist: trusty

compiler:
  - gcc

os:
  - linux

before_install:
  - echo $HOSTNAME

before_script:
- if [ $TRAVIS_OS_NAME == linux ]; then travis_retry make test; fi

script: 
  - make 
  - make test
  - ./oTravis 

notifications:
  email: false
