sudo: required

os:
  - linux

dist: trusty

services:
  - docker

language: cpp

compiler:
  - gcc

before_install:
  - docker pull ubuntu

before_script:
- if [ $TRAVIS_OS_NAME == linux ]; then travis_retry make test; fi

script: 
  - make test

notifications:
  email: false
