sudo: required

os:
  - linux

dist: trusty

services:
  - docker

language: cpp

compiler:
  - gcc

before_install:
  - docker pull ubuntu

before_script:
  - make test
  - ./oTravis
  - ls -l
  - uname -a
  - cat Makefile

script: 
  - docker version
  - docker start ubuntu
  - docker ps -a
  - docker exec ubuntu make test
  - docker exec ubuntu ./oTravis
  - docker exec ubuntu ls -l
  - docker stop ubuntu
  - docker ps -a

notifications:
  email: false
