sudo: required

os: linux

dist: trusty

services: docker

language: cpp

compiler: gcc

before_install:
  - docker pull ubuntu

install:
#  - docker build github.com/schneeheld/oTravis

before_script:
#  - make test
#  - ./oTravis
#  - ls -l
#  - uname -a
#  - cat Makefile

script: 
#  - docker version
  - docker images
  - docker run -d --name=ub1604 ubuntu
#  - docker run ubuntu
  - docker ps -a
  - docker exec ub1604 apt-get install g++
  - docker exec ub1604 g++ --version
  - docker exec ub1604 ls -l
  - docker exec ub1604 make test
  - docker exec ./oTravis
#  - docker exec ub1604 pwd
  - docker exec ub1604 cd /home
  - docker exec ub1604 ./oTravis
  - docker stop ub1604
  - docker ps -a
#  - docker run -it ubuntu
#  - apt-get update
#  - uname -a
#  - make test
  

notifications:
  email: false
